Rename the `object_struct` field labels and constants
pret/pokecrystal pull request #1005
Opened 2022-09-10 18:16 UTC by Rangi42

Fixes #990

2022-09-10 20:50 UTC, vulcandth requested changes
After that one requested change; I think this is good to merge. Thanks 👍

2022-09-10 20:50 UTC, vulcandth commented on constants/map_object_constants.asm
>  DEF OBJECT_1C                  rb ; 1c
```suggestion
DEF OBJECT_ANON_JUMPTABLE_INDEX                  rb ; 1c
```
You'll have to fix the formatting and the associated wram label, and everywhere it's used.

2022-09-10 20:50 UTC, vulcandth commented on constants/map_object_constants.asm
>  DEF OBJECT_1E                  rb ; 1e
These seem to be used for a couple purposes... One of which seems to store the address of the start of another object used in `StepFunction_TrackingObject`. So it's fine they remain as they are now.. just wanted to mention it.

2022-09-10 20:55 UTC, vulcandth commented on constants/map_object_constants.asm
>  DEF OBJECT_1C                  rb ; 1c
(If you agree with this, I can push the required changes to the PR for you. Since I know you are busy.)

2022-09-10 23:17 UTC, vulcandth approved these changes

2022-09-11 05:45 UTC, vulcandth approved these changes

2022-09-11 14:01 UTC, mid-kid commented
`CMDQUEUE_ANON_JUMPTABLE_INDEX` -> `CMDQUEUE_JUMPTABLE_INDEX` honestly. The only thing that makes it "anonymous" is an implementation detail.

2022-09-11 21:20 UTC, vulcandth approved these changes

2022-09-12 09:57 UTC, mid-kid approved these changes

2022-09-12 13:15 UTC, merged