Define relationship between map_object and object_events
pret/pokecrystal pull request #1054
Opened 2023-05-31 15:35 UTC by vulcandth

Opening this PR to further demonstrate what I'm suggesting should be done in issue #1031. Please review and look it over. If you don't think this is a good idea, or feel we want to have more conversation before this; feel free to close this PR or draft it.

Resolves #1031

2023-05-31 22:36 UTC, mid-kid commented
If you're moving `OBJECT_EVENT_SIZE` to be more closely related to `MAPOBJECT_*`, I'd name it something more apt like `MAPOBJECT_STRUCT_LENGTH` (we don't have a standard naming scheme for struct sizes...), and move all the other script command macros to their respective structure definitions, too, creating them where missing.

2023-06-22 16:24 UTC, Rangi42 commented on constants/map_object_constants.asm
> +DEF OBJECT_EVENT_SIZE EQU _RS - 1 ; object_event's begin with MAPOBJECT_SPRITE
```suggestion
DEF OBJECT_EVENT_SIZE EQU _RS - 1 ; skip MAPOBJECT_OBJECT_STRUCT_ID
```

2023-06-22 16:27 UTC, Rangi42 requested changes
Hmm. I liked keeping all the `*OBJECT_LENGTH` constants together. Although `object_event` fields do happen to correspond directly to a subset of `map_object` fields. How about changing script_constants.asm:

```
; An object_event is a map_object without its leading MAPOBJECT_OBJECT_STRUCT_ID
DEF OBJECT_EVENT_SIZE EQU MAPOBJECT_LENGTH - 1 ; 13
```

2023-06-22 16:28 UTC, Rangi42 commented
This is also an opportunity to define field constants for all of the warp/coord/bg/object event macros, instead of hard-coding their total sizes.

2023-06-23 15:42 UTC, vulcandth commented
> Hmm. I liked keeping all the `*OBJECT_LENGTH` constants together. Although `object_event` fields do happen to correspond directly to a subset of `map_object` fields. How about changing script_constants.asm:
> 
> ```
> ; An object_event is a map_object without its leading MAPOBJECT_OBJECT_STRUCT_ID
> DEF OBJECT_EVENT_SIZE EQU MAPOBJECT_LENGTH - 1 ; 13
> ```

Unfortunately It is without the leading `MAPOBJECT_OBJECT_STRUCT_ID` and the last two unused bytes at the end of the struct. (See the `rb_skip 2`).

So it would have to be something like:
```
DEF OBJECT_EVENT_SIZE EQU MAPOBJECT_LENGTH - 3 ; 13
```

2023-06-24 14:50 UTC, Rangi42 commented
I'm okay with this:
```
; An object_event is a map_object without its leading MAPOBJECT_OBJECT_STRUCT_ID or final padding
DEF OBJECT_EVENT_SIZE EQU MAPOBJECT_LENGTH - 3 ; 13
```

2023-08-14 10:40 UTC, mid-kid approved these changes

2023-08-14 13:42 UTC, Rangi42 approved these changes

2023-08-14 14:19 UTC, merged