Labeled Framesets and Constants Related
pret/pokecrystal pull request #1063
Opened 2023-08-02 03:24 UTC by SoupPotato

Updated all Framesets with labels.

2023-08-02 15:26 UTC, vulcandth requested changes
Great start; some feedback for now. I'll review it more when I get back home later.

2023-08-02 15:26 UTC, vulcandth commented on data/battle_anims/framesets.asm
> +	dw .Frameset_hit_big               ; BATTLEANIMFRAMESET_HIT_BIG
These labels, albeit local, point to an atomic chunk of code. So they should use .PascalCase and to also be consistent with the Frameset labels in `data/sprite_anims/framesets.asm`. We can leave the prefix `Framset_` with the underscore as this just aids in readability a little. This should be done for the rest as well.

```suggestion
    dw .Frameset_HitBig               ; BATTLEANIMFRAMESET_HIT_BIG
```

2023-08-02 15:26 UTC, vulcandth commented on data/battle_anims/objects.asm
> +;  ANIM_OBJ_CUT_UP_RIGHT
```suggestion
; ANIM_OBJ_CUT_UP_RIGHT
```

2023-08-02 15:26 UTC, vulcandth commented on data/battle_anims/objects.asm
> +; ANIM_OBJ_THUNDER_CENTER
You renamed some of the BattleAnimObjects in these comments... but you didn't actually update their constants with the new names.

2023-08-02 17:47 UTC, vulcandth commented on constants/battle_anim_constants.asm
>  	const BATTLEANIMFRAMESET_35
```suggestion
	const BATTLEANIMFRAMESET_THUNDER_WAVE_EXTRA
```

2023-08-03 12:21 UTC, Rangi42 commented on constants/battle_anim_constants.asm
>  	const BATTLEANIMFRAMESET_1E
If this were used, does it have a sensible name? Has it been useful in any custom anims?
```suggestion
	const BATTLEANIMFRAMESET_1E ; unused
```

2023-08-03 12:27 UTC, Rangi42 commented on constants/battle_anim_constants.asm
> +	const BATTLEANIMFRAMESET_UNUSED_MEGAPHONE
Following the pattern of other `git grep -E 'const .+UNUSED'` names.
```suggestion
	const BATTLEANIMFRAMESET_MEGAPHONE_UNUSED
```

2023-08-03 12:27 UTC, Rangi42 commented on constants/battle_anim_constants.asm
>  	const BATTLEANIMFRAMESET_B2
Same for this, does it have a descriptive name?

2023-08-03 12:28 UTC, Rangi42 commented on data/battle_anims/framesets.asm
> +	dw .Frameset_SprinningBone      ; BATTLEANIMFRAMESET_SPINNING_BONE
```suggestion
	dw .Frameset_SpinningBone       ; BATTLEANIMFRAMESET_SPINNING_BONE
```

2023-08-14 10:41 UTC, mid-kid commented
Just gonna comment that I like the naming scheme :)
So if I don't get around to properly reviewing this in the next week, consider this an approval.

2023-08-14 13:42 UTC, Rangi42 approved these changes

2023-08-21 16:09 UTC, vulcandth commented
Once I work out the conflicts when merging this to pokegold; i'll merge this.

2023-08-22 00:09 UTC, merged