Update bugs_and_glitches.md
pret/pokecrystal pull request #1099
Opened 2023-12-22 06:34 UTC by SoupPotato

Updated with new "`SFX_RUN` does not play correctly when a wild Pokemon flees from battle

2023-12-22 12:20 UTC, mid-kid commented
"the wrong command being used" -> "the wrong function being called"
That's the only comment I have towards this. I trust that this has been tested.

2023-12-22 13:29 UTC, SoupPotato commented
corrected, and yes it has been tested and works

2024-01-02 02:10 UTC, vulcandth requested changes

2024-01-02 02:10 UTC, vulcandth commented on docs/bugs_and_glitches.md
> +  - [`SFX_RUN` does not play correctly when a wild Pokemon flees from battle](#sfx_menu-does-not-play-correctly-when-a-awild-pokemon-flees-from-battle)
```suggestion
  - [`SFX_RUN` does not play correctly when a wild Pokemon flees from battle](#sfx_run-does-not-play-correctly-when-a-wild-pokemon-flees-from-battle)
```

2024-01-02 02:25 UTC, merged

2024-01-02 02:40 UTC, Rangi42 commented on docs/bugs_and_glitches.md
> +  - [`SFX_RUN` does not play correctly when a wild Pokemon flees from battle](#sfx_run-does-not-play-correctly-when-a-wild-pokemon-flees-from-battle)
Pokémon

2024-01-02 02:41 UTC, Rangi42 commented on docs/bugs_and_glitches.md
> +Due to the wrong function being called, `SFX_RUN` is never heard when a wild Pokemon flees from battle.
-

2024-01-02 02:41 UTC, Rangi42 commented on docs/bugs_and_glitches.md
> +.skip_text
Spaces