New MACRO Syntax
pret/pokecrystal pull request #905
Opened 2022-04-15 00:56 UTC by vulcandth

Implementing the new RGBDS Macro Syntax. This was done using regex. It `make compare` `OK`. Although, Please review thoroughly to make sure I didn't change something I shouldn't have.

Please also reference: #686

2022-04-17 00:15 UTC, Rangi42 commented
Looks good, thanks! I assume it was something like `s/^([A-Za-z_][A-Za-z0-9_@#]*): MACRO/MACRO \1/g`?

Please add `DEF` to constants in this PR as well. I thought that would be too disruptive, but after all, most constants are done with `const` and the `DEF`s would mostly be within macros anyway. A regex like `s/^([A-Za-z_][A-Za-z0-9_@#]*\s+(?:EQU\b|EQUS\b|=|rb\b|rw\b|rl\b))/DEF \1/g` should cover all of them, but then it'll be nice to manually indent ones inside of macros (since that's one reason rgbasm introduced the `DEF` syntax anyway).

2022-04-17 02:51 UTC, vulcandth commented
@Rangi42 I added DEF in front of the constants. I have not yet indented the constants in the MACRO's. I plan to go back through an manually tackling that. Could you please give one or two examples of how you like it indented.. and i'll apply it to the rest.

2022-04-17 03:57 UTC, Rangi42 commented
Oops, I forgot to get the new `+=`/`-=`/etc operators in that regex (like `__deco_value__ += 1`).

https://github.com/pret/pokecrystal/commit/ab0f9c287a45d1986985545d7ec6a2cd862e26fc

2022-04-17 05:26 UTC, Idain commented
I still think that Regex is advanced sorcery, so I'm very impressed.

2022-04-17 16:34 UTC, Rangi42 commented
I think this is ready now. @aaaaaa123456789 @mid-kid want to review?

> I still think that Regex is advanced sorcery, so I'm very impressed.

They're literally simpler than complete programming languages, it's just that they have a very dense syntax, and it can be hard to read which characters are regex language operators vs which are literal text. Python has a verbose regex mode that lets you space things out and add comments, like:

```
^                   # Start at the beginning of the line
(                   # Capture all this text so we can refer to it in the 'DEF \1' replacement
  [A-Za-z_]         # Constants start with a letter or '_'
  [A-Za-z0-9_@#] *  # Constants may then have letters, digits, '_'s, '@'s, or '#'s
  \s +              # At least one whitespace character between the constant and the operator
  [-+*/%<>&|^]      # The first character of '-=', '+=', '*=', etc
  =                 # The second character is always an '='
)
```

People have also made various [alternative syntaxes](https://lobste.rs/s/molbhc/alternative_regex_syntax) that some might find easier to read/write.

2022-04-20 20:06 UTC, aaaaaa123456789 requested changes
Noticed a few minor things. Nice work!

2022-04-20 20:06 UTC, aaaaaa123456789 commented on macros/vc.asm
> +MACRO vc_hook
Everything in this file needs reformatting (reindenting, etc.).

2022-04-20 20:06 UTC, aaaaaa123456789 commented on maps/CeladonGameCornerPrizeRoom.asm
> +DEF CELADONGAMECORNERPRIZEROOM_LARVITAR_COINS EQU 8888
These values should all be aligned.

2022-04-20 20:06 UTC, aaaaaa123456789 commented on maps/GoldenrodGameCorner.asm
> +DEF GOLDENRODGAMECORNER_WOBBUFFET_COINS EQU 1500
These values should all be aligned.

2022-04-20 20:06 UTC, aaaaaa123456789 commented on mobile/mobile_42.asm
> +	ld a, TRUE
Like with the other comment, whitespace pruning should be separate.

2022-04-20 20:06 UTC, aaaaaa123456789 commented on wram.asm
> +wCurBattleMon::
Same as before: keep whitespace pruning separate.

2022-04-21 01:02 UTC, vulcandth commented on engine/movie/intro.asm
>  endr
```assembly
.FastFadePalettes:
DEF hue = 31
rept 8
	RGB hue, hue, hue
	DEF hue -= 1
	RGB hue, hue, hue
	DEF hue -= 2
endr
```
Like this?

2022-04-26 20:15 UTC, Rangi42 commented
Updating the `MACRO` and `DEF` syntaxes here looks good to me. It should wait to merge until all four repos are ready.

2022-04-28 16:23 UTC, vulcandth reviewed
Noticed a couple things that still need fixing while doing pokegold.

2022-04-28 16:23 UTC, vulcandth commented on sram.asm
>  sBox{d:box_n}:: box sBox{d:box_n}
This line should be indented.

2022-06-06 21:25 UTC, merged